#!/bin/bash

data_root="$HOME/Downloads/data"

cluster_root="/cluster_data"

data-setup(){
	node_list=$1
	app_name=$2
	while read node; do
		echo $node
		ssh -n -tt "dcos@$node" "sudo mkdir -p ${cluster_root}
		sudo chmod -R 777 ${cluster_root}"
	done < "${node_list}"
}

data-list(){
	node_list=$1
	app_name=$2
	dirr=$3
	while read node; do
		echo $node
		ssh -n -tt "dcos@$node" "ls ${cluster_root}/${app_name}/${dirr}"
	done < "${node_list}"
}

put(){
	node_list=$1
	localdir=$2
	remotedir=$3
	while read node; do
		echo $node
		scp -r "${localdir}" "dcos@$node:${remotedir}" &
	done < "${node_list}"
	wait
}

pull-data(){
	app_name=$1
	node=$2
	echo $node
	scp -r "dcos@$node:${cluster_root}/${app_name}/output/" "${data_root}/${app_name}/"
}

delete(){
	node_list=$1
	app_name=$2
	while read node; do
		echo $node
		ssh -n -tt "dcos@$node" "rm -rf ${cluster_root}/${app_name}"
	done < "${node_list}"
}

clean(){
	node_list=$1
	app_name=$2
	dirr=$3
	while read node; do
		echo $node
		ssh -n -tt "dcos@$node" "sudo rm -rf ${cluster_root}/${app_name}/${dirr}/*"
	done < "${node_list}"
}

put-model(){
	node_list=$1
	app_name=$2
	put ${node_list} "${data_root}/${app_name}" "${cluster_root}/"
}

put-input(){
	node_list=$1
	app_name=$2
	folder=$3
	put ${node_list} "${data_root}/${app_name}/${folder}" "${cluster_root}/${app_name}/"
}

# verbatim script
$@